services:
    pinboard.cards_manager:
        class: PinboardBundle\Manager\CardsManager
        #dependecy injection: We inject a service inside another ( as constructor parameter ) and gain the ability to use all its features
        arguments: ['@doctrine.orm.entity_manager']
