user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

pinboard:
    resource: "@PinboardBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout
