user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

pinboard:
    resource: "@PinboardBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

logout:
    path: /logout
