security:
    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt

    providers:
        pinboard_db_provider:
            entity:
                class: UserBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        main:
            pattern:    ^/login
            http_basic: ~
            provider: pinboard_db_provider